# docker-compose.yml
version: '3.9'

services:
  influxdb2:
    image: influxdb:2
    container_name: influxdb2
    ports:
      - "8086:8086"
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: agri-insight
      DOCKER_INFLUXDB_INIT_BUCKET: bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-super-secret-auth-token

  mqtt:
    image: eclipse-mosquitto
    volumes:
      - mosquitto-data:/mosquitto/data
      - ./mosquitto:/mosquitto
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1884:1883"
      - "9002:9001"

  local-to-agg:
    image: telegraf:1.30
    container_name: telegraf
    depends_on:
      - influxdb2
      - mqtt
    links:
      - influxdb2
      - mqtt
    environment:
      LOCAL_MQTT_BROKER_URL: tcp://host.docker.internal:1883
      LOCAL_MQTT_USERNAME: admin
      LOCAL_MQTT_PASSWORD: admin
      LOCAL_MQTT_BROKER_ID: LB2
      AGG_MQTT_BROKER_URL: tcp://host.docker.internal:1884
      AGG_MQTT_USERNAME: admin
      AGG_MQTT_PASSWORD: admin
      INFLUXDB_URL: http://influxdb2:8086
      INFLUXDB_TOKEN: my-super-secret-auth-token
      INFLUXDB_ORG: agri-insight
      INFLUXDB_BUCKET: bucket
    volumes:
      - ./local-to-agg/telegraf.toml:/etc/telegraf/telegraf.conf:ro

volumes:
  influxdb2-data:
  influxdb2-config:
  mosquitto-data:
