[global_tags]
organization = "${INFLUXDB_ORG}"

[[inputs.mqtt_consumer]]

servers = [ "${MQTT_BROKER_URL}" ]
topics = [ "air/+/temperature", "soil/+/temperature" ]

username = "${MQTT_USERNAME}"
password = "${MQTT_PASSWORD}"

data_format = "json"

json_time_key = "timestamp"
json_time_format = "unix_ms"

[[inputs.mqtt_consumer.topic_parsing]]

topic = "+/+/+/+"
tags = "_/sensor_id/_/field"
measurement = "_/_/measurement/_"

[[outputs.influxdb_v2]]

urls = [ "${INFLUXDB_URL}" ]
timeout = "30s"
content_encoding = "gzip"

token = "${INFLUXDB_TOKEN}"
organization = "${INFLUXDB_ORG}"
bucket = "${INFLUXDB_BUCKET}"

tagexclude = [ "host", "topic" ]